Repository elastic/apm-agent-ruby, pull requests merged in 2018-05, with the labels that each got.

#109 Abbreviate http results
  lib/elastic_apm/middleware.rb
  spec/elastic_apm/middleware_spec.rb
Labels: [zube]: In Review, bug

#115 Instrument Resque Jobs
  lib/elastic_apm/agent.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/http.rb
  lib/elastic_apm/spies/resque.rb
  lib/elastic_apm/timed_worker.rb
  spec/elastic_apm/spies/resque_spec.rb
  spec/spec_helper.rb
Labels: [zube]: In Progress

#121 Don't instrument Mongo outside of transactions
  lib/elastic_apm/spies/mongo.rb
Labels: bug

#118 Provide summaries for more SQL queries
  lib/elastic_apm/normalizers/active_record.rb
  lib/elastic_apm/sql_summarizer.rb
  spec/elastic_apm/spies/sequel_spec.rb
  spec/elastic_apm/sql_summarizer_spec.rb
  spec/support/match_json_schema_matcher.rb
Labels: [zube]: In Review

#122 Remove ActiveSupport dependency
  Gemfile
  elastic-apm.gemspec
  lib/elastic_apm/config.rb
  spec/elastic_apm/subscriber_spec.rb
  spec/integration/rails_spec.rb
  spec/integration/sinatra_spec.rb
  spec/spec_helper.rb
Labels: [zube]: In Progress
