Repository elastic/apm-agent-ruby, pull requests merged in 2018-11, with the labels that each got.

#223 Add Transport::Worker
  Gemfile
  lib/elastic_apm/agent.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/config/duration.rb
  lib/elastic_apm/config/size.rb
  lib/elastic_apm/instrumenter.rb
  lib/elastic_apm/metadata.rb
  lib/elastic_apm/span.rb
  lib/elastic_apm/span_helpers.rb
  lib/elastic_apm/spies/delayed_job.rb
  lib/elastic_apm/stacktrace_builder.rb
  lib/elastic_apm/traceparent.rb
  lib/elastic_apm/transport/base.rb
  lib/elastic_apm/transport/connection.rb
  lib/elastic_apm/transport/filters.rb
  lib/elastic_apm/transport/serializers.rb
  lib/elastic_apm/transport/worker.rb
  spec/.jenkins_ruby.yml
  spec/elastic_apm/agent_spec.rb
  spec/elastic_apm/error_builder_spec.rb
  spec/elastic_apm/instrumenter_spec.rb
  spec/elastic_apm/span_helpers_spec.rb
  spec/elastic_apm/spies/delayed_job_spec.rb
  spec/elastic_apm/spies/sidekiq_spec.rb
  spec/elastic_apm/transport/base_spec.rb
  spec/elastic_apm/transport/connection_spec.rb
  spec/elastic_apm/transport/filters_spec.rb
  spec/elastic_apm/transport/serializers_spec.rb
  spec/elastic_apm/transport/worker_spec.rb
  spec/elastic_apm_spec.rb
  spec/integration/rails_spec.rb
  spec/integration/sinatra_spec.rb
  spec/scripts/cleanup.sh
  spec/spec_helper.rb
  spec/support/mock_intake.rb
Labels: [zube]: In Review

#230 Add sync and http props to Span::Context
  lib/elastic_apm/normalizers/active_record.rb
  lib/elastic_apm/span.rb
  lib/elastic_apm/span/context.rb
  lib/elastic_apm/spies/elasticsearch.rb
  lib/elastic_apm/spies/mongo.rb
  lib/elastic_apm/spies/sequel.rb
  lib/elastic_apm/transport/serializers/span_serializer.rb
  spec/elastic_apm/normalizers/active_record_spec.rb
  spec/elastic_apm/span/context_spec.rb
  spec/elastic_apm/spies/elasticsearch_spec.rb
  spec/elastic_apm/spies/mongo_spec.rb
  spec/elastic_apm/spies/sequel_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
Labels: [zube]: In Review, enhancement

#233 Update documentation for 2.0
  docs/api.asciidoc
  docs/configuration.asciidoc
  docs/context.asciidoc
  docs/custom-instrumentation.asciidoc
  docs/index.asciidoc
  docs/supported-technologies.asciidoc
  lib/elastic_apm.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/transaction.rb
Labels: [zube]: Inbox, docs

#234 🚨 Stop sending span.start, use timestamp
  lib/elastic_apm/span.rb
  lib/elastic_apm/transport/serializers/span_serializer.rb
  spec/elastic_apm/span_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
Labels: bug

#242 Fix code typo transaction->with_transaction
  docs/api.asciidoc
Labels: docs

#240 Truncate keyword fields to maximum 1024 chars
  CHANGELOG.md
  lib/elastic_apm/agent.rb
  lib/elastic_apm/context.rb
  lib/elastic_apm/context/request.rb
  lib/elastic_apm/context/request/socket.rb
  lib/elastic_apm/context/request/url.rb
  lib/elastic_apm/context/response.rb
  lib/elastic_apm/context/user.rb
  lib/elastic_apm/context_builder.rb
  lib/elastic_apm/metadata.rb
  lib/elastic_apm/metadata/process_info.rb
  lib/elastic_apm/metadata/service_info.rb
  lib/elastic_apm/metadata/system_info.rb
  lib/elastic_apm/span/context.rb
  lib/elastic_apm/stacktrace/frame.rb
  lib/elastic_apm/transport/base.rb
  lib/elastic_apm/transport/connection.rb
  lib/elastic_apm/transport/serializers.rb
  lib/elastic_apm/transport/serializers/context_serializer.rb
  lib/elastic_apm/transport/serializers/error_serializer.rb
  lib/elastic_apm/transport/serializers/metadata_serializer.rb
  lib/elastic_apm/transport/serializers/span_serializer.rb
  lib/elastic_apm/transport/serializers/transaction_serializer.rb
  lib/elastic_apm/transport/worker.rb
  lib/elastic_apm/util.rb
  spec/elastic_apm/context/user_spec.rb
  spec/elastic_apm/context_builder_spec.rb
  spec/elastic_apm/context_spec.rb
  spec/elastic_apm/instrumenter_spec.rb
  spec/elastic_apm/metadata/process_info_spec.rb
  spec/elastic_apm/metadata/service_info_spec.rb
  spec/elastic_apm/metadata/system_info_spec.rb
  spec/elastic_apm/spies/mongo_spec.rb
  spec/elastic_apm/transport/connection_spec.rb
  spec/elastic_apm/transport/serializers/error_serializer_spec.rb
  spec/elastic_apm/transport/serializers/metadata_serializer_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
  spec/elastic_apm/transport/serializers/transaction_serializer_spec.rb
  spec/elastic_apm/transport/serializers_spec.rb
  spec/elastic_apm/util_spec.rb
  spec/integration/rails_spec.rb
  spec/spec_helper.rb
Labels: [zube]: In Review

#249 Add support for Faraday
  lib/elastic_apm/config.rb
  lib/elastic_apm/spies/faraday.rb
  lib/elastic_apm/spies/net_http.rb
  spec/elastic_apm/spies/faraday_spec.rb
  spec/elastic_apm/spies/net_http_spec.rb
Labels: enhancement
