Repository elastic/apm-agent-ruby, pull requests merged in 2018-06, with the labels that each got.

#130 Add option to set min duration for span stacktrace collection
  docs/configuration.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/span.rb
  lib/elastic_apm/transaction.rb
  spec/elastic_apm/instrumenter_spec.rb
Labels: [zube]: In Review

#134 Fix logging and provide test for log options
  lib/elastic_apm/config.rb
  spec/elastic_apm/config_spec.rb
  spec/spec_helper.rb
Labels: [zube]: In Review

#140 Remove newline on hostname
  lib/elastic_apm/system_info.rb
  spec/elastic_apm/system_info_spec.rb
Labels: [zube]: In Review

#148 Abort posting payload when filter returns nil
  docs/api.asciidoc
  lib/elastic_apm/filters.rb
  lib/elastic_apm/http.rb
  spec/elastic_apm/filters_spec.rb
  spec/elastic_apm/http_spec.rb
Labels: [zube]: In Review

#150 Start mongodb for specs.
  spec/elastic_apm/spies/mongo_spec.rb
Labels: [zube]: In Review

#141 Use concurrent-ruby's TimerTask instead of home built
  CHANGELOG.md
  elastic-apm.gemspec
  lib/elastic_apm/agent.rb
  lib/elastic_apm/worker.rb
  spec/elastic_apm/worker_spec.rb
  spec/spec_helper.rb
Labels: [zube]: In Review, enhancement

#154 Add benchmark and profiling scripts
  .rubocop.yml
  Gemfile
  bench/.gitignore
  bench/app.rb
  bench/benchmark.rb
  bench/report.rb
  bench/rubyprof.rb
  bench/stackprof.rb
  bench/tmp/.gitkeep
  lib/elastic_apm/normalizers.rb
  spec/elastic_apm/spies/mongo_spec.rb
  spec/scripts/benchmarks.sh
Labels: [zube]: In Progress
