Repository elastic/apm-agent-ruby, pull requests merged in 2019-08, with the labels that each got.

#484 Central Config: Once more for Jenkins
  CHANGELOG.md
  docs/configuration.asciidoc
  lib/elastic_apm/agent.rb
  lib/elastic_apm/central_config.rb
  lib/elastic_apm/central_config/cache_control.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/config/options.rb
  spec/elastic_apm/central_config/cache_control_spec.rb
  spec/elastic_apm/central_config_spec.rb
Labels: [zube]: In Review, enhancement

#489 ci(jenkins): enable pre-commit and some pipeline changes
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
  .ci/jobs/apm-agent-ruby-downstream.yml
  .ci/jobs/apm-agent-ruby-mbp.yml
  .ci/jobs/defaults.yml
  .pre-commit-config.yaml
Labels: automation, ci, enhancement

#492 ci(jenkins): fix the unrelated error when using a reference repo
  .ci/downstreamTests.groovy
Labels: automation, bug, ci

#494 ci(jenkins): parentstream job should trigger the specific downstream jobs
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
Labels: automation, bug, ci

#497 ci(jenkins): GitHub check context split in parentstream and downstream
  .ci/jobs/apm-agent-ruby-downstream.yml
Labels: automation, ci

#502 feat: enable access to the jdk internals for the jruby docker images
  spec/scripts/spec.sh
Labels: automation, enhancement

#500 ci(jenkins): avoid using the any as the master-worker should be avoided
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
Labels: automation, ci, enhancement

#499 ci(jenkins): decouple test frameworks in stable and master
  .ci/.jenkins_framework.yml
  .ci/.jenkins_master_framework.yml
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
Labels: automation, ci, enhancement

#485 ci(jenkins): codecov should happen once, for ruby:2.6
  .ci/.jenkins_codecov.yml
  .ci/downstreamTests.groovy
Labels: automation, ci, enhancement

#503 ci(jenkins): use none as it's not required
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
Labels: automation, ci, enhancement

#508 ci(jenkins): git sha contains the merge commit
  .ci/Jenkinsfile
Labels: automation, bug, ci

#510 ci(jenkins): revert none agent
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
Labels: automation, bug, ci

#511 ci: check/remove-en-dashes pre-commit hooks are not required
  .pre-commit-config.yaml
Labels: automation, ci

#507 Return Error object from report
  CHANGELOG.md
  docs/api.asciidoc
  lib/elastic_apm.rb
  lib/elastic_apm/agent.rb
  spec/elastic_apm/agent_spec.rb
Labels: [zube]: In Review, enhancement

#487 Add Ruby VM specific metrics
  CHANGELOG.md
  docs/metrics.asciidoc
  lib/elastic_apm/metrics.rb
  lib/elastic_apm/metrics/vm.rb
  spec/elastic_apm/config_spec.rb
  spec/elastic_apm/instrumenter_spec.rb
  spec/elastic_apm/metrics/vm_spec.rb
  spec/elastic_apm/metrics_spec.rb
  spec/elastic_apm/span/context_spec.rb
  spec/elastic_apm/span_spec.rb
  spec/elastic_apm/trace_context_spec.rb
  spec/elastic_apm/transaction_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
  spec/elastic_apm_spec.rb
  spec/integration/rails_spec.rb
  spec/scripts/spec.sh
  spec/support/delegate_matcher.rb
Labels: [zube]: In Review, enhancement
