Repository elastic/apm-agent-ruby, pull requests merged in 2019-12, with the labels that each got.

#641 Add Ruby 2.7-rc (currently preview-3) to test matrix
  .ci/.jenkins_exclude.yml
  .ci/.jenkins_ruby.yml
Labels: [zube]: In Review, ci

#645 Remove set_tag from docs, replace with set_label
  docs/api.asciidoc
  docs/context.asciidoc
Labels: [zube]: In Review, docs

#646 ci(jenkins): transform tag name to the version
  .ci/Jenkinsfile
Labels: automation

#648 ci(jenkins): checkout master branch for the rebase
  .ci/prepare-git-context.sh
Labels: automation, ci

#571 Support starting more than one span on a transaction
  docs/api.asciidoc
  lib/elastic_apm.rb
  lib/elastic_apm/agent.rb
  lib/elastic_apm/child_durations.rb
  lib/elastic_apm/instrumenter.rb
  lib/elastic_apm/span.rb
  lib/elastic_apm/span/context.rb
  lib/elastic_apm/transaction.rb
  lib/elastic_apm/transport/serializers/span_serializer.rb
  spec/elastic_apm/agent_spec.rb
  spec/elastic_apm/transaction_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
  spec/elastic_apm_spec.rb
Labels: [zube]: In Review

#639 Rails stacktraces for controller actions
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/rails.rb
  lib/elastic_apm/spies/action_controller.rb
  spec/integration/rails_spec.rb
Labels: [zube]: In Progress

#647 Add span.context.destination to relevant spans
  CHANGELOG.asciidoc
  lib/elastic_apm/normalizers/rails/active_record.rb
  lib/elastic_apm/span/context.rb
  lib/elastic_apm/span/context/db.rb
  lib/elastic_apm/span/context/destination.rb
  lib/elastic_apm/span/context/http.rb
  lib/elastic_apm/spies/elasticsearch.rb
  lib/elastic_apm/spies/faraday.rb
  lib/elastic_apm/spies/http.rb
  lib/elastic_apm/spies/mongo.rb
  lib/elastic_apm/spies/net_http.rb
  lib/elastic_apm/spies/sequel.rb
  lib/elastic_apm/transport/serializers/span_serializer.rb
  spec/elastic_apm/span/context/destination_spec.rb
  spec/elastic_apm/span/context_spec.rb
  spec/elastic_apm/spies/elasticsearch_spec.rb
  spec/elastic_apm/spies/faraday_spec.rb
  spec/elastic_apm/spies/http_spec.rb
  spec/elastic_apm/spies/mongo_spec.rb
  spec/elastic_apm/spies/net_http_spec.rb
  spec/elastic_apm/spies/sequel_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
Labels: [zube]: In Progress, enhancement

#640 Improve SQL summarizing
  .gitignore
  .rubocop.yml
  CHANGELOG.asciidoc
  bench/sql.rb
  bin/build_docs
  docs/configuration.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/normalizers/rails/active_record.rb
  lib/elastic_apm/spies/sequel.rb
  lib/elastic_apm/sql.rb
  lib/elastic_apm/sql/signature.rb
  lib/elastic_apm/sql/tokenizer.rb
  lib/elastic_apm/sql/tokens.rb
  lib/elastic_apm/sql_summarizer.rb
  spec/elastic_apm/spies/sequel_spec.rb
  spec/elastic_apm/sql/signature_spec.rb
  spec/elastic_apm/sql/tokenizer_spec.rb
  spec/fixtures/sql_signature_examples.json
  spec/fixtures/sql_tokenizer_examples.json
  spec/integration/rails_spec.rb
  spec/spec_helper.rb
Labels: [zube]: In Review
