Repository elastic/apm-agent-ruby, pull requests merged in 2019-03, with the labels that each got.

#340 [APM-CI] progressive agent leasing
  Jenkinsfile
Labels: automation

#341 [APM-CI] build badge
  README.md
Labels: automation

#335 Generate dedicated Context for errors / Align capture_body config values
  CHANGELOG.md
  docs/api.asciidoc
  docs/configuration.asciidoc
  lib/elastic_apm.rb
  lib/elastic_apm/agent.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/context.rb
  lib/elastic_apm/context/user.rb
  lib/elastic_apm/context_builder.rb
  lib/elastic_apm/error.rb
  lib/elastic_apm/error_builder.rb
  lib/elastic_apm/middleware.rb
  lib/elastic_apm/spies/action_dispatch.rb
  lib/elastic_apm/transport/serializers/context_serializer.rb
  lib/elastic_apm/transport/serializers/error_serializer.rb
  spec/Dockerfile
  spec/elastic_apm/config_spec.rb
  spec/elastic_apm/context/user_spec.rb
  spec/elastic_apm/context_builder_spec.rb
  spec/elastic_apm/context_spec.rb
  spec/elastic_apm/error_builder_spec.rb
  spec/elastic_apm/error_spec.rb
  spec/elastic_apm/middleware_spec.rb
  spec/elastic_apm/transport/serializers/error_serializer_spec.rb
  spec/elastic_apm/transport/serializers/transaction_serializer_spec.rb
  spec/elastic_apm_spec.rb
  spec/integration/rails_spec.rb
  spec/spec_helper.rb
Labels: [zube]: In Review, enhancement

#343 Don't auto-start in Railtie if inside Rails' console
  CHANGELOG.md
  lib/elastic_apm/config.rb
  lib/elastic_apm/railtie.rb
  spec/.jenkins_exclude.yml
  spec/.jenkins_framework.yml
  spec/.jenkins_ruby.yml
  spec/integration/rails_spec.rb
Labels: [zube]: In Review

#349 [APM-CI] use current as pipeline shared library version
  Jenkinsfile
Labels: automation

#351 Fix reading available memory on Linux Kernel 3.2
  CHANGELOG.md
  lib/elastic_apm/metrics/cpu_mem.rb
  lib/elastic_apm/spies/faraday.rb
  spec/elastic_apm/metrics/cpu_mem_spec.rb
  spec/fixtures/proc_meminfo_wheezy
Labels: [zube]: In Review

#352 Add server proxy support
  CHANGELOG.md
  docs/configuration.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/transport/connection.rb
  spec/elastic_apm/transport/connection_spec.rb
Labels: [zube]: In Review, enhancement

#357 Fix stopping metrics when the are disabled
  CHANGELOG.md
  lib/elastic_apm/config.rb
  lib/elastic_apm/metrics.rb
  spec/elastic_apm/metrics_spec.rb
Labels: [zube]: In Review, bug

#363 Add config_file env setting
  CHANGELOG.md
  lib/elastic_apm/config.rb
Labels: [zube]: In Review, bug

#367 Allow proxy configuration by ENV
  CHANGELOG.md
  lib/elastic_apm/config.rb
Labels: [zube]: In Review, enhancement
