Repository elastic/apm-agent-ruby, pull requests merged in 2019-02, with the labels that each got.

#312 Add support for RHEL's /proc/stat format
  lib/elastic_apm/metrics/cpu_mem.rb
  spec/elastic_apm/metrics/cpu_mem_spec.rb
  spec/fixtures/proc_stat_debian
  spec/fixtures/proc_stat_rhel
Labels: [zube]: In Review

#313 Update contributing.md
  CHANGELOG.md
  CONTRIBUTING.md
Labels: [zube]: In Review, docs

#293 [APM-CI][Ruby] Pipeline version 0
  Jenkinsfile
  bench/report.rb
  spec/scripts/benchmarks.sh
Labels: automation

#325 [APM-CI] set workdir and HOME environment variable to point to /app
  Jenkinsfile
  spec/scripts/benchmarks.sh
Labels: automation

#328 [APM-CI] fix Exception to String conversion
  Jenkinsfile
Labels: automation

#334 [APM-CI] Bump shared lib version to 1.0.7
  Jenkinsfile
Labels: automation

#332 Force encode captured bodies to utf-8
  CHANGELOG.md
  lib/elastic_apm/context_builder.rb
  spec/elastic_apm/context_builder_spec.rb
Labels: [zube]: In Review, bug

#339 Fix request bodies with nested data
  CHANGELOG.md
  lib/elastic_apm/transport/filters/secrets_filter.rb
  spec/elastic_apm/transport/filters/secrets_filter_spec.rb
Labels: [zube]: In Review, bug

#338 Add `active` config option
  CHANGELOG.md
  docs/configuration.asciidoc
  lib/elastic_apm/agent.rb
  lib/elastic_apm/config.rb
  spec/elastic_apm/agent_spec.rb
Labels: [zube]: In Review, enhancement
