Repository elastic/apm-agent-ruby, pull requests merged in 2019-05, with the labels that each got.

#396 Let Faraday spy run with NetHTTPSpy disabled
  CHANGELOG.md
  lib/elastic_apm/spies/faraday.rb
Labels: [zube]: In Review

#397 Add disable_start_message config option
  CHANGELOG.md
  docs/configuration.asciidoc
  lib/elastic_apm/agent.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/railtie.rb
Labels: [zube]: In Review, enhancement

#398 Add more debug log messages
  lib/elastic_apm/agent.rb
  lib/elastic_apm/instrumenter.rb
  lib/elastic_apm/metrics.rb
Labels: [zube]: In Review

#399 Don't require ActionDispatch spy in railtie if disabled
  CHANGELOG.md
  lib/elastic_apm/config.rb
  lib/elastic_apm/railtie.rb
Labels: [zube]: In Review, bug

#400 Fix and streamline transport mocking in specs
  spec/elastic_apm/spies/faraday_spec.rb
  spec/elastic_apm/spies/http_spec.rb
  spec/elastic_apm/spies/net_http_spec.rb
  spec/elastic_apm/spies/rake_spec.rb
  spec/elastic_apm/spies/sidekiq_spec.rb
  spec/elastic_apm/transport/base_spec.rb
  spec/elastic_apm_spec.rb
  spec/integration/rails_spec.rb
  spec/spec_helper.rb
Labels: [zube]: In Review

#372 Rewrite Transport and Connection
  .rubocop.yml
  CHANGELOG.md
  lib/elastic_apm/agent.rb
  lib/elastic_apm/transport/base.rb
  lib/elastic_apm/transport/connection.rb
  lib/elastic_apm/transport/connection/http.rb
  lib/elastic_apm/transport/connection/proxy_pipe.rb
  lib/elastic_apm/transport/worker.rb
  spec/elastic_apm/transport/base_spec.rb
  spec/elastic_apm/transport/connection/http_spec.rb
  spec/elastic_apm/transport/connection/proxy_pipe_spec.rb
  spec/elastic_apm/transport/connection_spec.rb
  spec/elastic_apm/transport/worker_spec.rb
  spec/integration/rails_spec.rb
Labels: [zube]: In Review, docs, enhancement

#411 Throttle 'queue full' warnings to only once per 5 secs
  lib/elastic_apm/transport/base.rb
  lib/elastic_apm/util/throttle.rb
  spec/elastic_apm/util/throttle_spec.rb
Labels: [zube]: In Review

#405 Remove duplicate context section
  docs/api.asciidoc
Labels: docs

#418 Truncate error.culprit length
  CHANGELOG.md
  lib/elastic_apm/transport/serializers/error_serializer.rb
Labels: [zube]: In Review

#417 Reintroduce skipping events by returning nil in filter
  lib/elastic_apm/transport/filters.rb
  lib/elastic_apm/transport/worker.rb
  spec/elastic_apm/transport/filters_spec.rb
  spec/elastic_apm/transport/worker_spec.rb
Labels: [zube]: In Review, bug

#419 Align http User-Agent with other agents
  CHANGELOG.md
  lib/elastic_apm/transport/connection.rb
  spec/elastic_apm/transport/connection_spec.rb
Labels: [zube]: In Review

#424 Add option stack_trace_limit
  CHANGELOG.md
  lib/elastic_apm/config.rb
  lib/elastic_apm/stacktrace_builder.rb
  spec/elastic_apm/config_spec.rb
  spec/elastic_apm/stacktrace_builder_spec.rb
Labels: [zube]: In Review, enhancement

#423 Convert transaction.context.response.status_code to int
  CHANGELOG.md
  lib/elastic_apm/transport/serializers/context_serializer.rb
  spec/elastic_apm/transport/serializers/context_serializer_spec.rb
Labels: [zube]: In Review, bug

#403 [APM-CI][Integration test][Ruby] Support JRuby with different JDK versions
  .gitignore
  CONTRIBUTING.md
  Jenkinsfile
  spec/.jenkins_exclude.yml
  spec/.jenkins_ruby.yml
  spec/Dockerfile
  spec/scripts/benchmarks.sh
  spec/scripts/spec.sh
Labels: automation

#407 [APM-CI][All] Make the trigger by comment case-insensitive
  Jenkinsfile
Labels: automation

#413 Add debugging docs page
  docs/debugging.asciidoc
  docs/index.asciidoc
Labels: [zube]: In Review, docs

#414 Update benchmark script
  bench/app.rb
  bench/benchmark.rb
  bench/report.rb
  bench/stackprof.rb
  spec/scripts/benchmarks.sh
Labels: [zube]: In Progress

#431 Truncate span.context.db.statement to 10k chars
  CHANGELOG.md
  lib/elastic_apm/sql_summarizer.rb
  lib/elastic_apm/transport/serializers/span_serializer.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
Labels: bug
