Repository elastic/apm-agent-ruby, pull requests merged in 2019-11, with the labels that each got.

#596 [docs] fix pull link
  docs/release-notes.asciidoc
Labels: docs

#597 [2.x][docs] fix pull link (#596)
  docs/release-notes.asciidoc
Labels: docs

#603 Use connection_config instead to avoid retrieving a connection
  lib/elastic_apm/normalizers/rails/active_record.rb
  spec/elastic_apm/normalizers/active_record_spec.rb
Labels: [zube]: In Review

#600 Replace invalid bytes in SqlSummarizer
  lib/elastic_apm/sql_summarizer.rb
  spec/elastic_apm/sql_summarizer_spec.rb
Labels: [zube]: In Review

#587 Add MongoSpy unit test and move original test to integration
  spec/elastic_apm/spies/mongo_spec.rb
  spec/integration/mongo_spec.rb
Labels: [zube]: In Review

#615 Set remote_addr to immediate socket
  lib/elastic_apm/context/request/socket.rb
  spec/elastic_apm/context/request/socket_spec.rb
Labels: [zube]: In Review

#616 Clone HTTP cookies when building context
  CHANGELOG.asciidoc
  lib/elastic_apm/context_builder.rb
  spec/elastic_apm/context_builder_spec.rb
Labels: [zube]: In Review

#619 [jjbb] check_paths_for_matches.py not required anymore
  .ci/bin/check_paths_for_matches.py
Labels: automation, ci

#625 Add disable_metrics option
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/config/wildcard_pattern_list.rb
  lib/elastic_apm/metrics/set.rb
  spec/elastic_apm/config/wildcard_pattern_list_spec.rb
  spec/elastic_apm/metrics/set_spec.rb
Labels: [zube]: In Review, enhancement

#629 Sanitise auth info from outgoing HTTP requests' span.context.url
  CHANGELOG.asciidoc
  lib/elastic_apm/span/context.rb
  spec/elastic_apm/context/request/url_spec.rb
  spec/elastic_apm/span/context_spec.rb
Labels: [zube]: In Review

#636 Add mutex to Counter Metric
  .rubocop.yml
  CHANGELOG.asciidoc
  lib/elastic_apm/metrics/metric.rb
Labels: [zube]: In Review, bug

#631 ci(jenkins): trigger benchmark always and tweak whens
  .ci/Jenkinsfile
Labels: automation, ci

#635 ci(jenkins): trigger opbeans release process
  .ci/Jenkinsfile
Labels: automation, ci

#637 Correct span context collection name for Mongo getMore commands
  CHANGELOG.asciidoc
  lib/elastic_apm/spies/mongo.rb
  spec/integration/mongo_spec.rb
Labels: [zube]: In Review

#633 ci(jenkins): cancel previous running builds
  .ci/Jenkinsfile
Labels: automation, ci
