Repository elastic/apm-agent-ruby, pull requests merged in 2019-09, with the labels that each got.

#323 Remove type from exception message
  CHANGELOG.md
  lib/elastic_apm/error/exception.rb
  lib/elastic_apm/error_builder.rb
  spec/elastic_apm/error_builder_spec.rb
  spec/elastic_apm/transport/serializers/error_serializer_spec.rb
Labels: [zube]: In Review, breaking change

#516 ci(jenkins): Set GitHub notification context to apm-ci
  .ci/jobs/apm-agent-ruby-mbp.yml
Labels: automation, ci

#514 Change ext. types to external.
  CHANGELOG.md
  lib/elastic_apm/spies/faraday.rb
  lib/elastic_apm/spies/http.rb
  lib/elastic_apm/spies/net_http.rb
  spec/elastic_apm/spies/faraday_spec.rb
  spec/elastic_apm/spies/http_spec.rb
  spec/elastic_apm/spies/net_http_spec.rb
Labels: [zube]: In Review, breaking change

#518 Set config_file from ENV before loading
  CHANGELOG.md
  lib/elastic_apm/config.rb
  spec/elastic_apm/config_spec.rb
Labels: [zube]: In Progress, bug

#488 Support chained exceptions (copy for Jenkins, replaces #481)
  CHANGELOG.md
  lib/elastic_apm/error/exception.rb
  lib/elastic_apm/transport/serializers/error_serializer.rb
  spec/elastic_apm/error/exception_spec.rb
  spec/elastic_apm/transport/serializers/error_serializer_spec.rb
  spec/support/exception_helpers.rb
Labels: [zube]: Blocked

#520 ci(jenkins): decouple sanity check from CI pipeline
  .ci/Jenkinsfile
  .ci/jobs/apm-agent-ruby-linting-mbp.yml
  .ci/linting.groovy
Labels: automation, ci, enhancement

#519 Save passed config in VM collector
  lib/elastic_apm/metrics/vm.rb
Labels: [zube]: In Review, bug

#524 ci(jenkins): change the github comment for the linters
  .ci/linting.groovy
Labels: automation, ci

#525 Fix CentralConfig polling
  CHANGELOG.md
  lib/elastic_apm/agent.rb
  spec/elastic_apm/agent_spec.rb
Labels: [zube]: In Review, bug

#522 Extract Rails setup code into its own module so it can be called without Railtie
  CHANGELOG.md
  docs/api.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/rails.rb
  lib/elastic_apm/railtie.rb
  spec/elastic_apm/rails_spec.rb
Labels: [zube]: In Review

#531 Split span.type into type, subtype, action
  CHANGELOG.md
  docs/api.asciidoc
  lib/elastic_apm.rb
  lib/elastic_apm/agent.rb
  lib/elastic_apm/instrumenter.rb
  lib/elastic_apm/normalizers/action_controller.rb
  lib/elastic_apm/normalizers/action_mailer.rb
  lib/elastic_apm/normalizers/action_view.rb
  lib/elastic_apm/normalizers/active_record.rb
  lib/elastic_apm/span.rb
  lib/elastic_apm/spies/faraday.rb
  lib/elastic_apm/spies/http.rb
  lib/elastic_apm/spies/mongo.rb
  lib/elastic_apm/spies/net_http.rb
  lib/elastic_apm/subscriber.rb
  lib/elastic_apm/transport/serializers/span_serializer.rb
  spec/elastic_apm/agent_spec.rb
  spec/elastic_apm/normalizers/action_controller_spec.rb
  spec/elastic_apm/normalizers/action_view_spec.rb
  spec/elastic_apm/normalizers/active_record_spec.rb
  spec/elastic_apm/span_spec.rb
  spec/elastic_apm/spies/faraday_spec.rb
  spec/elastic_apm/spies/mongo_spec.rb
  spec/elastic_apm/spies/net_http_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
  spec/integration/rails_spec.rb
Labels: [zube]: In Review

#530 ci(jenkins): support release stage
  .ci/Jenkinsfile
  .ci/prepare-git-context.sh
Labels: automation, ci, enhancement

#538 Handle empty stacktrace frames when setting culprit
  CHANGELOG.md
  lib/elastic_apm/error_builder.rb
Labels: [zube]: In Review

#537 Use bundle/gem path to determine lib frames
  lib/elastic_apm/stacktrace_builder.rb
Labels: [zube]: In Review

#539 Rename disabled_spies to disabled_instrumentations
  CHANGELOG.md
  docs/configuration.asciidoc
  lib/elastic_apm/agent.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/rails.rb
  spec/elastic_apm/config_spec.rb
  spec/elastic_apm/spies/json_spec.rb
Labels: [zube]: In Review
