Repository elastic/apm-agent-ruby, pull requests merged in 2019-07, with the labels that each got.

#471 ci(jenkins): fix excludes on downstream job
  .ci/downstreamTests.groovy
Labels: automation, bug, ci

#477 ci: docs stage is handled within the elasticsearch-ci/docs
  .ci/Jenkinsfile
Labels: [zube]: In Review, automation, ci

#463 Refactor Config
  .rspec
  .rubocop.yml
  lib/elastic_apm/config.rb
  lib/elastic_apm/config/bytes.rb
  lib/elastic_apm/config/duration.rb
  lib/elastic_apm/config/options.rb
  lib/elastic_apm/config/regexp_list.rb
  lib/elastic_apm/config/size.rb
  lib/elastic_apm/normalizers/action_view.rb
  lib/elastic_apm/railtie.rb
  lib/elastic_apm/stacktrace_builder.rb
  lib/elastic_apm/transport/connection.rb
  spec/elastic_apm/config_spec.rb
  spec/elastic_apm/normalizers/action_view_spec.rb
  spec/elastic_apm/stacktrace_builder_spec.rb
  spec/elastic_apm/transport/connection_spec.rb
  spec/integration/rails_spec.rb
  spec/spec_helper.rb
Labels: [zube]: In Review, enhancement

#457 ci: launch parallel downstream jobs instead of parallel stages
  .ci/Jenkinsfile
  .ci/jobs/apm-agent-ruby-downstream.yml
  .ci/jobs/apm-agent-ruby-mbp.yml
  .ci/jobs/defaults.yml
Labels: [zube]: In Review, automation
