Repository elastic/apm-agent-ruby, pull requests merged in 2019-10, with the labels that each got.

#548 ci(jenkins): HOME env variable does not exist in the CI
  .ci/Jenkinsfile
Labels: automation, bug, ci, work in progress

#549 ci(jenkins): Reduce number of requested workers
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
  .ci/prepare-git-context.sh
Labels: automation, ci, work in progress

#547 Add example grok for trace IDs to log correlation docs
  docs/log-correlation.asciidoc
Labels: [zube]: In Review

#550 Use monotonic time to calculate durations
  .rubocop.yml
  CHANGELOG.md
  lib/elastic_apm/opentracing.rb
  lib/elastic_apm/span.rb
  lib/elastic_apm/transaction.rb
  lib/elastic_apm/util.rb
  spec/elastic_apm/span_spec.rb
  spec/elastic_apm/transaction_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
  spec/elastic_apm/transport/serializers/transaction_serializer_spec.rb
  spec/elastic_apm/util_spec.rb
  spec/integration/opentracing_spec.rb
  spec/support/mock_time.rb
Labels: [zube]: In Review, breaking change, enhancement

#555 ci(jenkins): disable benchmarking for the jruby:9.2
  .ci/Jenkinsfile
Labels: automation, ci

#559 [docs] Documentation restructure
  CHANGELOG.asciidoc
  docs/advanced.asciidoc
  docs/api.asciidoc
  docs/configuration.asciidoc
  docs/custom-instrumentation.asciidoc
  docs/debugging.asciidoc
  docs/getting-started-rack.asciidoc
  docs/getting-started-rails.asciidoc
  docs/index.asciidoc
  docs/introduction.asciidoc
  docs/opentracing.asciidoc
  docs/set-up.asciidoc
  docs/supported-technologies.asciidoc
Labels: docs

#564 [2.x][docs] Documentation restructure (#559)
  CHANGELOG.asciidoc
  docs/advanced.asciidoc
  docs/api.asciidoc
  docs/configuration.asciidoc
  docs/custom-instrumentation.asciidoc
  docs/debugging.asciidoc
  docs/getting-started-rack.asciidoc
  docs/getting-started-rails.asciidoc
  docs/index.asciidoc
  docs/introduction.asciidoc
  docs/opentracing.asciidoc
  docs/set-up.asciidoc
  docs/supported-technologies.asciidoc
Labels: docs

#578 Correct central config url path
  CHANGELOG.md
  lib/elastic_apm/central_config.rb
  spec/elastic_apm/central_config_spec.rb
Labels: [zube]: In Review, bug

#579 [2.x][docs] Add release notes to docs for 2.x
  CHANGELOG.asciidoc
  CHANGELOG.md
  docs/release-notes.asciidoc
Labels: docs

#580 Make sure to close spans after tests in OpenTracing spec
  lib/elastic_apm.rb
  lib/elastic_apm/central_config.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/logging.rb
  lib/elastic_apm/span.rb
  lib/elastic_apm/spies.rb
  lib/elastic_apm/transaction.rb
  lib/elastic_apm/transport/connection.rb
  lib/elastic_apm/transport/connection/http.rb
  lib/elastic_apm/transport/connection/proxy_pipe.rb
  lib/elastic_apm/transport/serializers.rb
  spec/integration/opentracing_spec.rb
Labels: [zube]: In Review

#588 ci(jenkins): add new framework test to the matrix
  .ci/.jenkins_framework.yml
Labels: automation, ci, test

#586 Fix logging in Rails apps, fix spec inconsistencies
  lib/elastic_apm.rb
  lib/elastic_apm/agent.rb
  lib/elastic_apm/central_config.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/error.rb
  lib/elastic_apm/error/exception.rb
  lib/elastic_apm/grape.rb
  lib/elastic_apm/instrumenter.rb
  lib/elastic_apm/metrics.rb
  lib/elastic_apm/metrics/cpu_mem.rb
  lib/elastic_apm/metricset.rb
  lib/elastic_apm/middleware.rb
  lib/elastic_apm/normalizers/grape/endpoint_run.rb
  lib/elastic_apm/rails.rb
  lib/elastic_apm/railtie.rb
  lib/elastic_apm/sinatra.rb
  lib/elastic_apm/span.rb
  lib/elastic_apm/util/prefixed_logger.rb
  spec/elastic_apm/metrics_spec.rb
  spec/elastic_apm/middleware_spec.rb
  spec/elastic_apm/rails_spec.rb
  spec/elastic_apm/sinatra_spec.rb
  spec/elastic_apm/spies/sidekiq_spec.rb
  spec/elastic_apm/transport/connection/http_spec.rb
  spec/elastic_apm/transport/serializers/error_serializer_spec.rb
  spec/elastic_apm/util/prefixed_logger_spec.rb
  spec/integration/grape_spec.rb
  spec/integration/rails_grape_spec.rb
  spec/integration/rails_spec.rb
  spec/integration/sinatra_spec.rb
  spec/scripts/spec.sh
  spec/spec_helper.rb
  spec/support/intercept.rb
  spec/support/with_agent.rb
Labels: [zube]: In Review, bug

#594 Fix configuration in Kibana requests
  CHANGELOG.asciidoc
  Gemfile
  lib/elastic_apm/central_config.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/transport/base.rb
  lib/elastic_apm/transport/connection.rb
  lib/elastic_apm/transport/connection/http.rb
  lib/elastic_apm/transport/headers.rb
  lib/elastic_apm/transport/user_agent.rb
  lib/elastic_apm/transport/worker.rb
  spec/elastic_apm/central_config_spec.rb
  spec/elastic_apm/transport/connection/http_spec.rb
  spec/elastic_apm/transport/connection_spec.rb
  spec/elastic_apm/transport/headers_spec.rb
  spec/elastic_apm/transport/user_agent_spec.rb
Labels: [zube]: In Review, bug

#593 Use the connection from payload to get adapter, when available
  lib/elastic_apm/normalizers/rails/active_record.rb
  spec/elastic_apm/normalizers/active_record_spec.rb
Labels: [zube]: In Progress
