Repository elastic/apm-agent-ruby, pull requests merged in 2019-06, with the labels that each got.

#435 feat(jenkins): new notifications and reports to Elasticsearch
  Jenkinsfile
Labels: [zube]: In Review, automation

#436 feat(jenkins): new notifications and reports to Elasticsearch
  Jenkinsfile
Labels: [zube]: In Review, automation

#442 feat(jenkins): GH Checks for the PR
  Jenkinsfile
Labels: automation

#439 [docs][7.2] update environment docs
  docs/configuration.asciidoc
Labels: docs

#440 Fix Http.rb < 4 support
  CHANGELOG.md
  lib/elastic_apm/transport/connection/proxy_pipe.rb
  spec/elastic_apm/transport/connection/proxy_pipe_spec.rb
Labels: [zube]: In Review, bug

#449 Fix disabling verifying server certificate
  CHANGELOG.md
  lib/elastic_apm/transport/connection.rb
  spec/elastic_apm/transport/connection_spec.rb
Labels: [zube]: In Review, bug

#448 Save request cookies on context, filter cookies in headers
  CHANGELOG.md
  lib/elastic_apm/context_builder.rb
  lib/elastic_apm/transport/filters/secrets_filter.rb
  spec/elastic_apm/context_builder_spec.rb
  spec/elastic_apm/transport/filters/secrets_filter_spec.rb
Labels: [zube]: In Review

#451 ci(jenkins): trigger async ITs and update github check for the pull request
  Jenkinsfile
Labels: automation

#452 Release original backtrace regardless of used or not
  lib/elastic_apm/span.rb
Labels: [zube]: In Review

#393 ci(jenkins): [WIP] move CI related files to .ci folder
  .ci/.jenkins_exclude.yml
  .ci/.jenkins_framework.yml
  .ci/.jenkins_ruby.yml
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
  .ci/jobs/apm-agent-ruby-downstream.yml
  .ci/jobs/defaults.yml
Labels: [zube]: Ready, automation

#453 ci: add the jenkinsfile again to the root folder
  .ci/jobs/apm-agent-ruby-downstream.yml
  .ci/jobs/apm-agent-ruby-mbp.yml
  Jenkinsfile
Labels: automation

#454 ci: create new CI jobs
  .ci/jobs/defaults.yml
Labels: automation

#455 ci: fix syntax errors on downstream job
  .ci/downstreamTests.groovy
Labels: automation

#456 ci: downstream job
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
  Jenkinsfile
Labels: automation

#460 Use default cert store if no CA specified
  CHANGELOG.md
  lib/elastic_apm/transport/connection.rb
Labels: [zube]: In Review

#458 ci(jenkins): enable pull requests using the upstream repo
  .ci/Jenkinsfile
Labels: automation

#459 ci(jenkins): notify first time contributor github check
  .ci/Jenkinsfile
Labels: automation
