Repository elastic/apm-agent-ruby, pull requests merged in 2020-04, with the labels that each got.

#736 Cobertura coverage
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
  Rakefile
  codecov.yml
  spec/scripts/coverage_converge.sh
  spec/scripts/coverage_entrypoint.sh
  spec/scripts/spec.sh
  spec/spec_helper.rb
  vendor/.gitkeep
Labels: automation, ci

#757 ci(jenkins): merge branch in downstream jobs
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
  .ci/jobs/defaults.yml
Labels: automation, bug, ci

#760 docs: add dynamic badge to configuration options
  docs/configuration.asciidoc
  docs/images/dynamic-config.svg
Labels: docs

#770 ci(jenkins): refactor with withGitRelease step
  .ci/Jenkinsfile
  .ci/prepare-git-context.sh
Labels: automation, ci

#780 ci(jenkins): avoid converge if only docs
  .ci/Jenkinsfile
Labels: automation, bug, ci

#781 ci: fix downstream notifications
  .ci/downstreamTests.groovy
Labels: automation, bug, ci

#778 docs: Add performance tuning documentation
  docs/index.asciidoc
  docs/performance-tuning.asciidoc
Labels: docs
