Repository elastic/apm-agent-ruby, pull requests merged in 2020-05, with the labels that each got.

#785 ci: reduce log verbosity
  .ci/Jenkinsfile
Labels: [zube]: In Review, automation, ci

#784 Put env var config for rails on the main page
  docs/getting-started-rails.asciidoc
Labels: docs, review

#790 ci: use withEnv to overwrite the HOME env var
  .ci/Jenkinsfile
Labels: automation, bug, ci

#793 fix: add a new checkout stage only for tags on downstream jobs
  .ci/downstreamTests.groovy
Labels: automation, bug, ci

#794 fix: make a play checkout on tag
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
Labels: automation, bug, ci

#799 test: google-protobuf >=3.12 supports for ruby >=2.5
  Gemfile
Labels: automation, test

#795 ci: use matrix instead downstreams
  .ci/Jenkinsfile
  .ci/downstreamTests.groovy
  docker-compose.yml
  spec/scripts/spec.sh
Labels: automation, ci

#802 ci: run ITs and master tests in parallel
  .ci/Jenkinsfile
Labels: automation, ci

#804 Net::HTTP spy: Allow underscores in hostnames
  CHANGELOG.asciidoc
  lib/elastic_apm/spies/net_http.rb
  spec/elastic_apm/spies/net_http_spec.rb
Labels: [zube]: In Review, bug
