Repository elastic/apm-agent-ruby, pull requests merged in 2020-02, with the labels that each got.

#704 Enrich existing GitHub templates
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: [zube]: Inbox, automation

#694 Support TraceContext and tracestate
  lib/elastic_apm/agent.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/middleware.rb
  lib/elastic_apm/opentracing.rb
  lib/elastic_apm/spies/faraday.rb
  lib/elastic_apm/spies/http.rb
  lib/elastic_apm/spies/net_http.rb
  lib/elastic_apm/trace_context.rb
  lib/elastic_apm/trace_context/traceparent.rb
  lib/elastic_apm/trace_context/tracestate.rb
  spec/elastic_apm/middleware_spec.rb
  spec/elastic_apm/spies/faraday_spec.rb
  spec/elastic_apm/spies/http_spec.rb
  spec/elastic_apm/spies/net_http_spec.rb
  spec/elastic_apm/trace_context/traceparent_spec.rb
  spec/elastic_apm/trace_context/tracestate_spec.rb
  spec/elastic_apm/trace_context_spec.rb
  spec/elastic_apm/transaction_spec.rb
  spec/integration/opentracing_spec.rb
Labels: [zube]: In Review, enhancement

#708 Add sanitize_fields_names and soft deprecate custom_key_filters
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/config/wildcard_pattern_list.rb
  lib/elastic_apm/transport/filters/secrets_filter.rb
  spec/elastic_apm/config/wildcard_pattern_list_spec.rb
  spec/elastic_apm/config_spec.rb
  spec/elastic_apm/transport/filters/secrets_filter_spec.rb
Labels: [zube]: In Review, enhancement

#709 [docs] Deprecation note for custom_key_filters
  docs/configuration.asciidoc
Labels: docs

#668 Include number of `rows_affected` in span db context for Sequel
  CHANGELOG.asciidoc
  lib/elastic_apm/span/context/db.rb
  lib/elastic_apm/spies/sequel.rb
  lib/elastic_apm/transport/serializers/span_serializer.rb
  spec/elastic_apm/spies/sequel_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
Labels: [zube]: In Review

#710 ci(jenkins): wait for the Gem to be available when a release happens
  .ci/Jenkinsfile
Labels: automation, bug, ci

#713 Adding missing links
  docs/set-up.asciidoc
Labels: docs

#716 [docs] Attribute bug fix
  docs/supported-technologies.asciidoc
Labels: docs

#717 [docs] Fix typo
  docs/api.asciidoc
Labels: docs

#715 [docs] Add EOL table to documentation
  CHANGELOG.md
  CONTRIBUTING.md
  docs/index.asciidoc
  docs/upgrading.asciidoc
Labels: docs

#723 JRuby docker images
  .ci/docker/jruby/11-jdk/Dockerfile
  .ci/docker/jruby/12-jdk/Dockerfile
  .ci/docker/jruby/13-jdk/Dockerfile
  .ci/docker/jruby/7-jdk/Dockerfile
  .ci/docker/jruby/8-jdk/Dockerfile
  .ci/docker/jruby/README.md
  .ci/docker/jruby/run.sh
  .ci/docker/jruby/test.sh
  .gitignore
Labels: automation

#718 ci(jenkins): run opbeans validation per PR
  .ci/Jenkinsfile
Labels: automation

#727 ci(jenkins): apm-its-downstream params has changed
  .ci/Jenkinsfile
Labels: automation
