Repository elastic/apm-agent-ruby, pull requests merged in 2020-10, with the labels that each got.

#874 Fix DelayedJob with no running agent
  CHANGELOG.asciidoc
  lib/elastic_apm/spies/delayed_job.rb
  spec/elastic_apm/spies/delayed_job_spec.rb
Labels: [zube]: In Review, bug

#854 test: synchronizing json spec
  spec/elastic_apm/sql/tokenizer_spec.rb
  spec/fixtures/sql_signature_examples.json
  spec/fixtures/sql_token_examples.json
Labels: automation

#853 test: synchronizing gherkin spec
  features/api_key.feature
Labels: automation

#871 Add cloud provider metadata
  CHANGELOG.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/metadata.rb
  lib/elastic_apm/metadata/cloud_info.rb
  lib/elastic_apm/transport/connection.rb
  lib/elastic_apm/transport/serializers/metadata_serializer.rb
  lib/elastic_apm/transport/user_agent.rb
  lib/elastic_apm/transport/worker.rb
  lib/elastic_apm/util.rb
  spec/elastic_apm/central_config_spec.rb
  spec/elastic_apm/metadata/cloud_info_spec.rb
  spec/elastic_apm/spies/elasticsearch_spec.rb
  spec/elastic_apm/spies/faraday_spec.rb
  spec/elastic_apm/spies/http_spec.rb
  spec/elastic_apm/spies/net_http_spec.rb
  spec/elastic_apm/transport/connection/http_spec.rb
  spec/elastic_apm/transport/connection_spec.rb
  spec/elastic_apm/transport/serializers/metadata_serializer_spec.rb
  spec/elastic_apm/util_spec.rb
  spec/integration/rails_logger_spec.rb
  spec/integration/rails_metrics_stress_spec.rb
  spec/integration/rails_paths_spec.rb
  spec/integration/rails_spec.rb
  spec/spec_helper.rb
  spec/support/event_collector.rb
  spec/support/mock_intake.rb
Labels: [zube]: In Review
