Repository elastic/apm-agent-ruby, pull requests merged in 2020-01, with the labels that each got.

#666 Add reference repo for apm-agent-ruby
  .ci/Jenkinsfile
  .ci/jobs/apm-agent-ruby-downstream.yml
  .ci/jobs/apm-agent-ruby-linting-mbp.yml
  .ci/jobs/apm-agent-ruby-mbp.yml
Labels: automation, ci

#671 Serialize Span Context labels
  lib/elastic_apm/transport/serializers/span_serializer.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
Labels: [zube]: In Review, bug

#674 Add support for shoryuken (AWS SQS)
  .gitignore
  CHANGELOG.asciidoc
  Gemfile
  docs/supported-technologies.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/spies/shoryuken.rb
  spec/elastic_apm/spies/shoryuken_spec.rb
Labels: [zube]: In Review, enhancement

#675 Convert Response HTTP header values to string
  CHANGELOG.asciidoc
  lib/elastic_apm/context/response.rb
  spec/elastic_apm/context/response_spec.rb
Labels: bug

#676 Add support for Sneakers
  CHANGELOG.asciidoc
  Gemfile
  docs/supported-technologies.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/spies/sneakers.rb
  spec/elastic_apm/spies/sneakers_spec.rb
Labels: [zube]: In Review, enhancement

#655 Support api keys
  CHANGELOG.asciidoc
  Gemfile
  docs/configuration.asciidoc
  features/api_key.feature
  features/step_definitions/stepdefs.rb
  features/support/env.rb
  lib/elastic_apm/config.rb
  lib/elastic_apm/transport/headers.rb
  spec/elastic_apm/central_config_spec.rb
  spec/elastic_apm/transport/connection_spec.rb
  spec/elastic_apm/transport/headers_spec.rb
Labels: [zube]: In Progress

#678 ci(jenkins): disable CodeCov comments on PRs
  .codecov.yml
Labels: automation, ci

#680 ci(jenkins): mount the reference repo volume for the release with a docker container
  .ci/Jenkinsfile
  .ci/prepare-git-context.sh
Labels: automation

#684 Update TOC in Readme
  README.md
Labels: docs

#683 ci(jenkins): even load distribution for the timeouts
  .ci/Jenkinsfile
Labels: automation, ci

#682 ci(jenkins): notify downstream timeout and test failure issues
  .ci/Jenkinsfile
Labels: automation, ci

#692 [benchmark] some fixes in the CI
  .ci/Jenkinsfile
  .gitignore
  spec/scripts/benchmarks.sh
Labels: automation, bug, ci

#693 ci(jenkins): enable benchmarking for the jruby:9.2
  .ci/Jenkinsfile
Labels: automation, bug, ci

#698 Enable docker image cache in the CI workers
  .ci/packer_cache.sh
  spec/scripts/spec.sh
Labels: automation, ci
