Repository elastic/apm-agent-ruby, pull requests merged in 2020-03, with the labels that each got.

#728 ci(jenkins): use one docker-compose
  docker-compose.yml
  spec/docker-compose.yml
  spec/scripts/benchmarks.sh
  spec/scripts/spec.sh
Labels: automation, ci

#730 Use the new SQL parser as default
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/sql.rb
  spec/elastic_apm/config_spec.rb
  spec/elastic_apm/spies/sequel_spec.rb
Labels: [zube]: In Review, enhancement

#731 ci(jenkins): run the ITs earlier
  .ci/Jenkinsfile
Labels: automation

#732 ci(jenkins): decouple post-release steps in the rake release step
  .ci/Jenkinsfile
  CONTRIBUTING.md
  Rakefile
Labels: automation, ci

#721 Add GraphQL support
  .rubocop.yml
  CHANGELOG.asciidoc
  Gemfile
  docs/graphql.asciidoc
  docs/index.asciidoc
  lib/elastic_apm.rb
  lib/elastic_apm/graphql.rb
  spec/integration/graphql_spec.rb
  spec/integration/rails_console_spec.rb
  spec/support/with_env.rb
Labels: enhancement

#734 ci(jenkins): load utils function with the retry and fix update-branch
  .ci/Jenkinsfile
  Rakefile
Labels: automation, bug, ci

#742 docs: Add link to Agent/Server compatibility
  docs/introduction.asciidoc
Labels: docs

#745 ci(jenkins): disable stages for only docs
  .ci/Jenkinsfile
Labels: automation
