Repository elastic/apm-agent-ruby, pull requests merged in 2020-11, with the labels that each got.

#885 Strip null values in cloud metadata
  CHANGELOG.asciidoc
  Gemfile
  lib/elastic_apm/transport/serializers/metadata_serializer.rb
  spec/elastic_apm/transport/serializers/metadata_serializer_spec.rb
Labels: [zube]: In Review

#896 Handle invalid utf-8 byte sequences in sql summarizer and DB statement
  CHANGELOG.asciidoc
  lib/elastic_apm/span/context/db.rb
  lib/elastic_apm/sql/signature.rb
  spec/elastic_apm/span/context_spec.rb
  spec/elastic_apm/sql/signature_spec.rb
Labels: agent-ruby

#898 Update url for fetching json schema from apm-server repo
  spec/support/match_json_schema_matcher.rb
Labels: agent-ruby

#890 Use Module#prepend where possible
  Gemfile
  lib/elastic_apm.rb
  lib/elastic_apm/central_config.rb
  lib/elastic_apm/config/regexp_list.rb
  lib/elastic_apm/config/wildcard_pattern_list.rb
  lib/elastic_apm/span_helpers.rb
  lib/elastic_apm/spies/action_dispatch.rb
  lib/elastic_apm/spies/dynamo_db.rb
  lib/elastic_apm/spies/elasticsearch.rb
  lib/elastic_apm/spies/faraday.rb
  lib/elastic_apm/spies/http.rb
  lib/elastic_apm/spies/net_http.rb
  lib/elastic_apm/spies/rake.rb
  lib/elastic_apm/spies/redis.rb
  lib/elastic_apm/spies/resque.rb
  lib/elastic_apm/spies/sequel.rb
  lib/elastic_apm/spies/sidekiq.rb
  lib/elastic_apm/spies/sinatra.rb
  lib/elastic_apm/spies/tilt.rb
  lib/elastic_apm/stacktrace_builder.rb
  lib/elastic_apm/util/deep_dup.rb
  spec/support/mock_intake.rb
Labels: [zube]: In Review, agent-ruby, breaking change

#902 Handle both int and string log level, and extra central config values
  lib/elastic_apm/config.rb
  lib/elastic_apm/config/log_level_map.rb
  spec/elastic_apm/central_config_spec.rb
  spec/elastic_apm/config/log_level_map_spec.rb
  spec/elastic_apm/config_spec.rb
  spec/integration/rails_spec.rb
Labels: agent-ruby

#904 Add changelog entry for log level changes
  CHANGELOG.asciidoc
Labels: agent-ruby

#908 Rename server_ca_cert to server_ca_cert_file
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  lib/elastic_apm/config.rb
  spec/elastic_apm/config_spec.rb
Labels: agent-ruby
