Repository elastic/apm-agent-ruby, pull requests merged in 2020-06, with the labels that each got.

#789 Elasticsearch client integration: Use body in db statement
  docs/configuration.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/spies/elasticsearch.rb
  lib/elastic_apm/transport/filters/hash_sanitizer.rb
  lib/elastic_apm/transport/filters/secrets_filter.rb
  spec/elastic_apm/spies/elasticsearch_spec.rb
Labels: discussion, enhancement

#813 ci: run benchmark on a PR basis if comment
  .ci/Jenkinsfile
Labels: automation

#791 Update Opentracing bridge
  CHANGELOG.asciidoc
  lib/elastic_apm/opentracing.rb
  spec/integration/opentracing_spec.rb
Labels: [zube]: In Progress

#805 Temporarily disable grpc spec
  Gemfile
  lib/elastic_apm/grpc.rb
  spec/elastic_apm/grpc_spec.rb
  spec/support/helloworld_pb.rb
  spec/support/helloworld_services_pb.rb
Labels: [zube]: In Progress

#820 Add service_node_name
  CHANGELOG.asciidoc
  docs/configuration.asciidoc
  lib/elastic_apm/config.rb
  lib/elastic_apm/metadata/service_info.rb
  lib/elastic_apm/transport/serializers/metadata_serializer.rb
  spec/elastic_apm/metadata/service_info_spec.rb
  spec/elastic_apm/transport/serializers/metadata_serializer_spec.rb
Labels: enhancement

#819 fix: check that docker is installed
  .ci/packer_cache.sh
Labels: [zube]: In Review, automation, bug, ci
