Repository elastic/apm-agent-ruby, pull requests merged in 2021-04, with the labels that each got.

#886 chore(ci): automate BDD tests in CI pipeline
  .ci/Jenkinsfile
  bin/run-bdd
  bin/run-tests
  features/step_definitions/api_key_steps.rb
  spec/scripts/features.sh
Labels: agent-ruby, automation, ci

#1000 synchronize schema spec
  spec/fixtures/transaction.json
Labels: agent-ruby, automation

#1002 CI: Skip JRuby 9.2x + Sinatra 1.4
  .ci/.jenkins_exclude.yml
Labels: agent-ruby

#1006 Add set_service API
  .ci/.jenkins_exclude.yml
  CHANGELOG.asciidoc
  lib/elastic_apm.rb
  lib/elastic_apm/agent.rb
  lib/elastic_apm/grpc.rb
  lib/elastic_apm/normalizers/rails/active_record.rb
  lib/elastic_apm/span.rb
  lib/elastic_apm/span/context.rb
  lib/elastic_apm/span/context/destination.rb
  lib/elastic_apm/spies/dynamo_db.rb
  lib/elastic_apm/spies/elasticsearch.rb
  lib/elastic_apm/spies/http.rb
  lib/elastic_apm/spies/mongo.rb
  lib/elastic_apm/spies/net_http.rb
  lib/elastic_apm/spies/s3.rb
  lib/elastic_apm/spies/sequel.rb
  lib/elastic_apm/spies/sns.rb
  lib/elastic_apm/spies/sqs.rb
  lib/elastic_apm/transport/serializers/span_serializer.rb
  spec/elastic_apm/span/context/destination_spec.rb
  spec/elastic_apm/span/context_spec.rb
  spec/elastic_apm/span_spec.rb
  spec/elastic_apm/spies/dynamo_db_spec.rb
  spec/elastic_apm/spies/elasticsearch_spec.rb
  spec/elastic_apm/spies/faraday_spec.rb
  spec/elastic_apm/spies/http_spec.rb
  spec/elastic_apm/spies/mongo_spec.rb
  spec/elastic_apm/spies/net_http_spec.rb
  spec/elastic_apm/spies/s3_spec.rb
  spec/elastic_apm/spies/sequel_spec.rb
  spec/elastic_apm/spies/sns_spec.rb
  spec/elastic_apm/spies/sqs_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
  spec/elastic_apm_spec.rb
Labels: agent-ruby

#1004 SQL: Parse CQL comments
  CHANGELOG.asciidoc
  lib/elastic_apm/sql/tokenizer.rb
  spec/fixtures/sql_token_examples.json
Labels: agent-ruby, automation

#1005 Update configuration.asciidoc
  docs/configuration.asciidoc
Labels: agent-ruby, docs

#1007 Read cloud metadata on Azure App Services
  CHANGELOG.asciidoc
  lib/elastic_apm/metadata/cloud_info.rb
  spec/elastic_apm/metadata/cloud_info_spec.rb
Labels: agent-ruby
