Repository elastic/apm-agent-ruby, pull requests merged in 2021-02, with the labels that each got.

#956 Specify branch when installing rails gem from main
  Gemfile
Labels: agent-ruby

#955 Limit version of i18n gem because of JRuby refinements bug
  Gemfile
Labels: agent-ruby

#952 Rescue when failing to get DelayedJob job name
  lib/elastic_apm/spies/delayed_job.rb
Labels: agent-ruby

#961 docs: Add cloud_provider documentation
  docs/configuration.asciidoc
Labels: agent-ruby, docs

#959 Remove support for legacy Traceparent args
  lib/elastic_apm/opentracing.rb
  lib/elastic_apm/trace_context.rb
  lib/elastic_apm/trace_context/traceparent.rb
  spec/elastic_apm/span_spec.rb
  spec/elastic_apm/spies/faraday_spec.rb
  spec/elastic_apm/spies/http_spec.rb
  spec/elastic_apm/spies/net_http_spec.rb
  spec/elastic_apm/trace_context/traceparent_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
  spec/integration/opentracing_spec.rb
Labels: agent-ruby

#963 ci: use the releaseNotification step
  .ci/Jenkinsfile
Labels: agent-ruby, automation, ci

#968 Fix GraphQL spec
  spec/integration/graphql_spec.rb
Labels: agent-ruby

#962 Default to localhost when Host missing
  CHANGELOG.asciidoc
  docs/supported-technologies.asciidoc
  lib/elastic_apm/span/context/http.rb
  lib/elastic_apm/spies/faraday.rb
  lib/elastic_apm/spies/net_http.rb
  spec/elastic_apm/spies/faraday_spec.rb
  spec/elastic_apm/spies/net_http_spec.rb
Labels: agent-ruby

#969 test: synchronizing gherkin spec
  features/outcome.feature
Labels: agent-ruby, automation
