Repository elastic/apm-agent-ruby, pull requests merged in 2021-03, with the labels that each got.

#974 synchronize schema spec
  spec/fixtures/error.json
  spec/fixtures/metadata.json
  spec/fixtures/metricset.json
  spec/fixtures/span.json
  spec/fixtures/transaction.json
Labels: agent-ruby, automation

#953 Fix missing ActiveRecord connection object in notification payload
  CHANGELOG.asciidoc
  lib/elastic_apm/normalizers/rails/active_record.rb
  spec/elastic_apm/normalizers/active_record_spec.rb
  spec/elastic_apm/spies/shoryuken_spec.rb
Labels: agent-ruby

#980 Fix the heading sequence
  CHANGELOG.asciidoc
Labels: agent-ruby

#982 test: synchronizing gherkin spec
  features/azure_app_service_metadata.feature
Labels: agent-ruby, automation

#985 Updates from running rubocop on latest PR merge (cont.)
  CHANGELOG.asciidoc
  lib/elastic_apm/normalizers/rails/active_record.rb
  spec/elastic_apm/normalizers/active_record_spec.rb
Labels: agent-ruby

#971 Update outcome cucumber spec
  .rubocop.yml
  features/outcome.feature
  features/step_definitions/api_key_steps.rb
  features/step_definitions/common_steps.rb
  features/step_definitions/outcome_steps.rb
Labels: agent-ruby

#986 Update DynamoDB Spy to match AWS services spec (cont.)
  CHANGELOG.asciidoc
  lib/elastic_apm/naively_hashable.rb
  lib/elastic_apm/span/context/destination.rb
  lib/elastic_apm/spies/dynamo_db.rb
  lib/elastic_apm/transport/serializers/span_serializer.rb
  spec/elastic_apm/spies/dynamo_db_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
Labels: agent-ruby

#987 Add instrumentation for AWS S3 (cont.)
  CHANGELOG.asciidoc
  Gemfile
  lib/elastic_apm/config.rb
  lib/elastic_apm/spies/s3.rb
  spec/elastic_apm/spies/s3_spec.rb
Labels: agent-ruby

#988 Add instrumentation for AWS SQS and SNS (cont.)
  CHANGELOG.asciidoc
  Gemfile
  lib/elastic_apm/config.rb
  lib/elastic_apm/span/context.rb
  lib/elastic_apm/span/context/message.rb
  lib/elastic_apm/spies/sns.rb
  lib/elastic_apm/spies/sqs.rb
  lib/elastic_apm/transport/serializers/span_serializer.rb
  spec/elastic_apm/span/context_spec.rb
  spec/elastic_apm/spies/sns_spec.rb
  spec/elastic_apm/spies/sqs_spec.rb
  spec/elastic_apm/transport/serializers/span_serializer_spec.rb
Labels: agent-ruby

#992 docs: update for 4.x
  README.md
  docs/upgrading.asciidoc
Labels: agent-ruby, docs

#994 docs: jump table
  docs/release-notes.asciidoc
Labels: agent-ruby
