Repository elastic/apm-agent-ruby, pull requests merged in 2023-04, with the labels that each got.

#1366 Migrate Jenkinsfile 2 GH Actions Workflow
  .ci/.jenkins_exclude.yml
  .ci/.jenkins_ruby.yml
  .ci/.jenkins_ruby_benchmarks.yml
  .ci/Jenkinsfile
  .ci/scripts/install-build-system.sh
  .ci/snapshoty.yml
  .github/workflows/ci.yml
  .github/workflows/coverage-reporter.yml
  .github/workflows/opentelemetry.yml
  .github/workflows/release.yml
  .github/workflows/run-matrix.yml
  .github/workflows/snapshoty.yml
  .github/workflows/test-reporter.yml
  bin/run-tests
  spec/scripts/spec.sh
Labels: agent-ruby

#1380 Remove jenkins related precommit hooks
  .pre-commit-config.yaml
Labels: agent-ruby

#1379 Update status badge
  README.md
Labels: agent-ruby

#1381 docs: remove kibana endpoint enabled requirement
  docs/configuration.asciidoc
Labels: agent-ruby, Team:Docs

#1385 fix: don't fail on unpullable images
  .ci/packer_cache.sh
Labels: ci, agent-ruby
